version: "3"

services:
  db:
    container_name: postgres
    image: postgres:12
    hostname: ${PGHOST}
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5433:5432'

  node:
    container_name: node
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/home/node/oharvest
      - node_module:/home/node/oharvest/node_modules
    ports:
      - ${PORT}:${PORT}
    command:
      - ${ENVIRONMENT:-start}
    depends_on:
      - db

volumes:
  db_data:
  node_module:


